apiVersion: v1
kind: Pod
metadata:
  name: "ravendb-cluster-creator"
  namespace: ravendb
  labels:
    app.kubernetes.io/name: ravendb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  restartPolicy: OnFailure
  volumes:
    - name: ravendb-scripts
      configMap:
        name: ravendb-scripts
    - name: ravendb-setup-package
      secret:
        secretName: ravendb-setup-package
  containers:
  - name: main
    image: "ubuntu:latest" # todo: use lighter distro to run the scripts
    command: ["/bin/bash"]
    args: ["/ravendb/scripts/create-cluster.sh"]
    volumeMounts:
      - name: ravendb-scripts
        mountPath: /ravendb/scripts
      - name: ravendb-setup-package
        mountPath: /ravendb/ravendb-setup-package
